from django.urls import path

from .views import (
    ArchiveListCreateView,
    DashboardView,
    DeleteSharedFolderView,
    DeleteSharedDocumentView,
    DocumentActionSummaryView,
    DocumentDetailView,
    DocumentExportPdfView,
    DocumentListCreateView,
    DocumentOnlyOfficeCallbackView,
    DocumentOnlyOfficeConfigView,
    DocumentDownloadView,
    DocumentUploadView,
    ExportJobDownloadView,
    ForceUnlockDocumentView,
    LockDocumentView,
    PersonalLibraryListView,
    PersonalLibraryMountDetailView,
    PersonalLibraryMountListCreateView,
    PersonalLibraryMountSyncView,
    PersonalLibraryOnlyOfficeConfigView,
    PersonalLibrarySessionDownloadView,
    PersonalLibrarySessionForceSaveView,
    PersonalLibrarySessionOnlyOfficeCallbackView,
    PersonalLibrarySessionStatusView,
    PersonalLibrarySyncView,
    RecycleBinListView,
    PurgeRecycleEntryView,
    RestoreArchiveEntryView,
    RestoreRecycleEntryView,
    SharedTreeView,
    SharedFolderDetailView,
    SharedFolderListCreateView,
    SharedPermissionDetailView,
    SharedPermissionListCreateView,
)


urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("tree/", SharedTreeView.as_view(), name="shared-tree"),
    path("personal/", PersonalLibraryListView.as_view(), name="personal-library"),
    path("personal/mounts/", PersonalLibraryMountListCreateView.as_view(), name="personal-library-mounts"),
    path("personal/mounts/<int:pk>/", PersonalLibraryMountDetailView.as_view(), name="personal-library-mount-detail"),
    path("personal/mounts/<int:pk>/sync/", PersonalLibraryMountSyncView.as_view(), name="personal-library-mount-sync"),
    path("personal/sync/", PersonalLibrarySyncView.as_view(), name="personal-library-sync"),
    path("personal/<int:pk>/onlyoffice-config/", PersonalLibraryOnlyOfficeConfigView.as_view(), name="personal-onlyoffice-config"),
    path("personal-sessions/<str:session_id>/status/", PersonalLibrarySessionStatusView.as_view(), name="personal-session-status"),
    path("personal-sessions/<str:session_id>/download/", PersonalLibrarySessionDownloadView.as_view(), name="personal-session-download"),
    path("personal-sessions/<str:session_id>/forcesave/", PersonalLibrarySessionForceSaveView.as_view(), name="personal-session-forcesave"),
    path("personal-sessions/<str:session_id>/onlyoffice-callback/", PersonalLibrarySessionOnlyOfficeCallbackView.as_view(), name="personal-session-onlyoffice-callback"),
    path("folders/", SharedFolderListCreateView.as_view(), name="folders"),
    path("folders/<int:pk>/", SharedFolderDetailView.as_view(), name="folder-detail"),
    path("permissions/", SharedPermissionListCreateView.as_view(), name="permissions"),
    path("permissions/<int:pk>/", SharedPermissionDetailView.as_view(), name="permission-detail"),
    path("documents/", DocumentListCreateView.as_view(), name="documents"),
    path("documents/upload/", DocumentUploadView.as_view(), name="document-upload"),
    path("documents/<int:pk>/", DocumentDetailView.as_view(), name="document-detail"),
    path("documents/<int:pk>/summary/", DocumentActionSummaryView.as_view(), name="document-summary"),
    path("documents/<int:pk>/download/", DocumentDownloadView.as_view(), name="document-download"),
    path("documents/<int:pk>/export-pdf/", DocumentExportPdfView.as_view(), name="document-export-pdf"),
    path("documents/<int:pk>/onlyoffice-config/", DocumentOnlyOfficeConfigView.as_view(), name="document-onlyoffice-config"),
    path("documents/<int:pk>/onlyoffice-callback/", DocumentOnlyOfficeCallbackView.as_view(), name="document-onlyoffice-callback"),
    path("exports/<int:pk>/download/", ExportJobDownloadView.as_view(), name="export-job-download"),
    path("recycle-bin/", RecycleBinListView.as_view(), name="recycle-bin"),
    path("recycle-bin/<int:pk>/restore/", RestoreRecycleEntryView.as_view(), name="recycle-restore"),
    path("recycle-bin/<int:pk>/purge/", PurgeRecycleEntryView.as_view(), name="recycle-purge"),
    path("documents/<int:pk>/lock/", LockDocumentView.as_view(), name="lock-document"),
    path("documents/<int:pk>/force-unlock/", ForceUnlockDocumentView.as_view(), name="force-unlock-document"),
    path("documents/<int:pk>/delete/", DeleteSharedDocumentView.as_view(), name="delete-shared-document"),
    path("folders/<int:pk>/delete/", DeleteSharedFolderView.as_view(), name="delete-shared-folder"),
    path("archive/", ArchiveListCreateView.as_view(), name="archive"),
    path("archive/<int:pk>/restore/", RestoreArchiveEntryView.as_view(), name="archive-restore"),
]
