# Generated by Django 5.2.9 on 2026-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='cos_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='recyclebinentry',
            name='recycled_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
